-- SQL script to create the admin table in PostgreSQL
-- Run this script in pgAdmin4 or your PostgreSQL client
-- Database: GestureLab

-- Create admin table
CREATE TABLE IF NOT EXISTS admin (
    id SERIAL PRIMARY KEY,
    full_name VARCHAR(100) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Create indexes for faster lookups
CREATE INDEX IF NOT EXISTS idx_admin_username ON admin(username);
CREATE INDEX IF NOT EXISTS idx_admin_email ON admin(email);

-- Insert default admin account (optional - the app will create it automatically if it doesn't exist)
-- Password: Rose@123 (hashed)
-- Note: The actual password hash will be generated by the application
-- INSERT INTO admin (full_name, username, email, password) 
-- VALUES ('Rose Khatiwada', 'Rose', 'rkc123@gmail.com', '<hashed_password>');

-- Note: The application will automatically create the default admin account on startup
-- if no admin exists in the database. The password is hashed using bcrypt.
